# Generated by Django 5.2 on 2026-04-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "description_short",
                    models.CharField(
                        max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "description_long",
                    models.TextField(verbose_name="Полное описание"),
                ),
                ("lng", models.FloatField(verbose_name="Долгота")),
                ("lat", models.FloatField(verbose_name="Широта")),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
    ]
