# Generated by Django 5.2 on 2026-04-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "places",
            "0007_rename_description_long_place_long_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
                verbose_name="Место",
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["position"], name="places_imag_positio_b2104b_idx"
            ),
        ),
    ]
